#server.port=8088
#spring.thymeleaf.cache=false
#
#spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://106.55.171.55:3306/stealthy_striver_db_v2?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
#spring.datasource.username=test
#spring.datasource.password=mediading
#spring.datasource.hikari.minimum-idle=5
#spring.datasource.hikari.maximum-pool-size=15
#spring.datasource.hikari.auto-commit=true
#spring.datasource.hikari.idle-timeout=30000
#spring.datasource.hikari.pool-name=hikariCP
#spring.datasource.hikari.max-lifetime=600000
#spring.datasource.hikari.connection-timeout=30000
#spring.datasource.hikari.connection-test-query=SELECT 1
#
#mybatis.type-aliases-package=com.ading_keki.stealthy_striver.pojo
#mybatis.mapper-locations=classpath:mapper/*Mapper.xml

server:
  port: 8088

spring:
  thymeleaf:
    cache: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.55.171.55:3306/stealthy_striver_db_v2?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: test
    password: mediading
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: hikariCP
      max-lifetime: 600000
      connection-timeout: 30000
      connection-test-query: SELECT 1
mybatis:
  type-aliases-package: com.ading_keki.stealthy_striver.pojo
  mapper-locations: classpath:mapper/*Mapper.xml